/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uy.edu.ort.gradle.test;

import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(App.class.getResource("/cifar-14.png").getFile());
        Persona p=new Persona();
        // p.setNombre("marcos");
        // System.out.println(p.getNombre());
        System.out.println(StringUtils.equals("marcos", "marcos"));
        
    }
}
